# Generated by Django 2.2.12 on 2020-05-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Skus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[(1, 'BLACK'), (2, 'RED'), (3, 'BLUE'), (4, 'GREEN'), (5, 'YELLOW')], max_length=5)),
                ('price_min', models.IntegerField()),
                ('price_max', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
