# Generated by Django 2.2.12 on 2020-05-07 13:43

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200507_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skus',
            name='color',
            field=models.CharField(choices=[(products.models.ColorChoice('Black'), 'Black'), (products.models.ColorChoice('Red'), 'Red'), (products.models.ColorChoice('Green'), 'Green'), (products.models.ColorChoice('Blue'), 'Blue'), (products.models.ColorChoice('Yellow'), 'Yellow')], max_length=10),
        ),
    ]
