# Generated by Django 2.2.12 on 2020-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200507_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='skus',
            name='size',
            field=models.CharField(choices=[('XXS', 'XX-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XXL', 'XX-Large')], default='Small', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skus',
            name='color',
            field=models.CharField(choices=[('BLACK', 'Black'), ('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('YELLOW', 'Yellow')], max_length=10),
        ),
    ]
